name: example
description: example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  dynamic_forms:
    path: ../../dynamic_forms

dev_dependencies:
  build_runner: ^2.0.6
  dynamic_forms_generator:
    path: ../
