name: example
description: A flutter example of dynamic forms project with default components.
version: 0.2.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_dynamic_forms_components:
    path: ../
  flutter_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/test_form1.xml
    - assets/test_form1.json
    - assets/transition_form1.xml
    - assets/transition_form2.xml
    - assets/transition_form3.xml
