language: dart
os:
  - linux
sudo: required
dist: trusty
dart:
  - 2.12.2
addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
  - chmod +x scripts/code_coverage.sh
script:
  - cd packages/expression_language
  - pub get
  - ../../scripts/code_coverage.sh
  - cp coverage/lcov.info ../../expression_language.lcov
  - cd ../dynamic_forms
  - pub get
  - ../../scripts/code_coverage.sh
  - cp coverage/lcov.info ../../dynamic_forms.lcov
  - cd ../flutter_dynamic_forms
  - flutter pub get
  - flutter test
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
