name: dynamic_forms
description: Dart library providing infrastructure to parse complex external form with expressions into a custom model.
version: 1.0.0
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^5.0.0
  rxdart: ^0.26.0

  expression_language:
    path: ../expression_language
  collection: ^1.15.0
  
dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
