name: dynamic_forms
description: Dart library providing infrastructure to parse complex external form with expressions into a custom model.
version: 1.0.0
homepage: https://github.com/markphillips100/flutter_dynamic_forms
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  xml: ^6.5.0
  rxdart: ^0.26.0
  meta: ^1.3.0
  collection: ^1.19.1

  expression_language:
    # path: ../expression_language/
    git:
      url: https://github.com/markphillips100/flutter_dynamic_forms.git
      path: packages/expression_language

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0
