name: example
description: A flutter example of dynamic forms project with custom components.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_dynamic_forms:
    path: ../
  collection: ^1.15.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/test_form1.xml
