name: flutter_dynamic_forms_components
description: Flutter package containing default set of dynamic form components.
version: 0.12.0
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  rxdart: ^0.26.0
  intl: ^0.17.0
  collection: ^1.15.0
  
  expression_language:
    git:
      url: https://github.com/markphillips100/flutter_dynamic_forms.git
      ref: null-safety
      path: packages/expression_language
  dynamic_forms:
    git:
      url: https://github.com/markphillips100/flutter_dynamic_forms.git
      ref: null-safety
      path: packages/dynamic_forms
  flutter_dynamic_forms:
    git:
      url: https://github.com/markphillips100/flutter_dynamic_forms.git
      ref: null-safety
      path: packages/flutter_dynamic_forms

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  pedantic: ^1.8.0+1
  dynamic_forms_generator:
    path: ../dynamic_forms_generator
    # git:
    #   url: https://github.com/markphillips100/flutter_dynamic_forms.git
    #   ref: null-safety
    #   path: packages/dynamic_forms_generator

flutter:
