name: dynamic_forms_generator
description: Library for generating model and parser part of the dynamic forms.
version: 1.0.0
homepage: https://github.com/markphillips100/flutter_dynamic_forms

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  build: ^2.0.0
  yaml: ^3.1.0
  petitparser: ^5.1.0
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.8
