name: dynamic_forms_generator
description: Library for generating model and parser part of the dynamic forms.
version: 0.7.0
homepage: https://github.com/OndrejKunc/flutter_dynamic_forms

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.0
  build_config: ">=0.2.6 <0.5.0"
  yaml: ^3.1.0
  petitparser: ^4.0.2
  meta: ^1.3.0

dev_dependencies:
  test: ^1.6.3
  pedantic: ^1.9.0
