name: flutter_dynamic_forms
description: A flutter project providing infrastructure to render dynamic forms.
version: 1.0.0
homepage: https://github.com/markphillips100/flutter_dynamic_forms
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  provider: ^6.0.0

  dynamic_forms:
    git:
      url: https://github.com/markphillips100/flutter_dynamic_forms.git
      path: packages/dynamic_forms
  expression_language:
    git:
      url: https://github.com/markphillips100/flutter_dynamic_forms.git
      path: packages/expression_language

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
