name: flutter_dynamic_forms
description: A flutter project providing infrastructure to render dynamic forms.
version: 0.12.0
homepage: https://github.com/markphillips100/flutter_dynamic_forms

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  provider: ^5.0.0

  expression_language:
    git:
      url: https://github.com/markphillips100/flutter_dynamic_forms.git
      path: packages/expression_language
  dynamic_forms:
    git:
      url: https://github.com/markphillips100/flutter_dynamic_forms.git
      path: packages/dynamic_forms

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
