name: expression_language
description: Library for parsing and evaluating simple expression language with additional references
version: 0.3.0
homepage: https://github.com/markphillips100/flutter_dynamic_forms

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  petitparser: ^4.0.2
  rational: ^0.3.7
  meta: ^1.1.8

dev_dependencies:
  test: ^1.9.4
  test_coverage: ^0.4.0
  gherkin: ^1.1.5+1
  glob: ^1.2.0
  pedantic: ^1.9.0
