name: expression_language
description: Library for parsing and evaluating simple expression language with additional references
version: 1.0.1
homepage: https://github.com/markphillips100/flutter_dynamic_forms

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  petitparser: ^6.1.0
  rational: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.21.4
  gherkin: ^3.1.0
  glob: ^2.1.0
  decimal: ^2.0.0
