name: expression_language
description: Library for parsing and evaluating simple expression language with additional references
version: 1.0.1
homepage: https://github.com/markphillips100/flutter_dynamic_forms

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  petitparser: ^5.1.0
  rational: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.21.4
  gherkin: ^3.1.0
  glob: ^2.1.0
